config/routes.rb
FirehoseApp::Application.routes.draw do

   root 'static_pages#index'
   resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	mount_uploader :image, PicUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

	def index
		@pics = Pic.all
	end

	def new
		@pic = Pic.new
	end

	def create
		# Pic.create(:hour => 1,
		# 	:emotion => "",
		#   :learned => "")
		Pic.create(pics_params)
		redirect_to pics_path
	end

	private

	def pics_params
		params.require(:pic).permit(:hour, :emotion, :learned, :image)
	end
	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Learning Coding</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
	 
		<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
		<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		</a>
		 
		<!-- Be sure to leave the brand out there if you want it shown -->
		<%= link_to 'Learning Coding', root_path, :class => 'brand' %>
		 
		<!-- Everything you want hidden at 940px or less, place within here -->
		<div class="nav-collapse collapse">
		<!-- .nav, .navbar-search, .navbar-form, etc -->
		<ul class="nav">
			<li>
				<%= link_to 'Entries', pics_path %>
			</li>
			<li>
				<%= link_to 'Submit New Image', new_pic_path %>
			</li>
		</ul>

		</div>
		 
		</div>
	</div>
</div>

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<% @pics.each do |pic| %>
	<div class="span4 text-center shadowed-box-entries">
		<h1 class="custom-splash-font">
			Hour: <%= pic.hour %>
		</h1>

		<%= image_tag pic.image %>

		<h2>
			<br />
			Emotion: <%= pic.emotion %>
			<br />
			<br />
			Learned: <%= pic.learned %>
		</h2>
	</div>
<% end %>

app/views/pics/new.html.erb
<div class="row-fluid">
	<div class="span6 offset3 text-center shadowed-box">
		<h1 class="custom-splash-font">
			Add your update!
		</h1>

		<br />
		<%= simple_form_for @pic do |f| %>
			<%= f.input :hour, label: 'Enter the hour:', placeholder: '1, 2, 3, etc.' %>
			<%= f.input :image, label: 'Selfie:' %>
			<%= f.input :emotion, label: 'How do you feel?', placeholder: 'Stoked, excited, confused' %>
			<%= f.input :learned, label: 'What did you learn?', placeholder: 'HTML, CSS3, Rails, Github' %>
		<br />
			<%= f.submit 'Save', :class => 'btn btn-large btn-warning' %>
		<% end %>
	</div>
</div>

app/views/static_pages/index.html.erb
<div class="row-fluid">

	<div class="span6 offset3 text-center shadowed-box">

		<h1 class="custom-splash-font">Hi, I'm Michael.</h1>

		<h2 class="">I'm having a blast learning how to code.</h2>
		<br />
		<%= link_to 'Launch!', '/pics', :class => 'btn btn-large btn-success' %>

	</div>
	
</div>